[package]
name = "domain-database-seaorm"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
shared = { path = "../shared" }
domain = { path = "../domain" }
database-seaorm = { path = "../database-seaorm" }
sea-orm.workspace = true
async-trait.workspace = true
chrono.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
anyhow.workspace = true
database-seaorm-migration = { path = "../database-seaorm-migration" }
sea-orm = { workspace = true, features = ["sqlx-sqlite"] }
sea-orm-migration = { workspace = true, features = ["sqlx-sqlite"] }
