[package]
name = "domain-database-seaorm"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
database-seaorm = { path = "../database-seaorm" }
domain = { path = "../domain" }
rust_decimal.workspace = true
sea-orm.workspace = true
serde_json.workspace = true
shared = { path = "../shared" }
uuid.workspace = true

[dev-dependencies]
anyhow.workspace = true
database-seaorm-migration = { path = "../database-seaorm-migration" }
sea-orm = { workspace = true, features = ["sqlx-sqlite"] }
sea-orm-migration = { workspace = true, features = ["sqlx-sqlite"] }
tokio.workspace = true
