[workspace]
resolver = "3"
members = ["crates/*", "packages/endpoint-tauri/endpoint-tauri"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Ukonn Ra <ukonnra@outlook.com>"]

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
itertools = "0.14"
proc-macro2 = "1.0"
quote = "1.0"
rust_decimal = { version = "1.41", features = ["serde-str", "macros"] }
sea-orm = { version = "2.0.0-rc.37", features = ["runtime-tokio", "macros", "with-chrono", "with-json", "with-rust_decimal", "with-uuid"] }
sea-orm-migration = { version = "2.0.0-rc.37", features = ["runtime-tokio"] }
serde = { version = "1.0", features = ["rc", "derive"] }
serde_json = "1.0"
strum = { version = "0.28", features = ["derive"] }
syn = { version = "2.0", features = ["full"] }
thiserror = "2.0"
tokio = { version = "1.50", features = ["full"] }
uuid = { version = "1.23", features = ["v7"] }
