sonar.projectKey=UkonnRa_white-rabbit
sonar.organization=ukonnra
sonar.projectName=White Rabbit
sonar.projectVersion=0.1.0

sonar.sources=crates
sonar.exclusions=crates/**/*_test.rs,crates/**/test.rs

sonar.tests=crates
sonar.test.inclusions=crates/**/*_test.rs,crates/**/test.rs
sonar.rust.lcov.reportPaths=lcov.info
