import type { ComponentRecipe } from "../../types";

export const tagInputRecipe: ComponentRecipe = {
  base: [],
  variants: {
    root: [
      "flex",
      "flex-wrap",
      "items-center",
      "gap-1.5",
      "w-full",
      "rounded-xl",
      "border",
      "border-outline-variant",
      "bg-surface-container",
      "px-3",
      "py-1.5",
      "transition-colors",
      "duration-normal",
      "ease-standard",
      "focus-within:border-primary",
      "focus-within:outline-2",
      "focus-within:outline-offset-0",
      "focus-within:outline-primary",
    ],
    chip: [
      "inline-flex",
      "items-center",
      "gap-0.5",
      "rounded-full",
      "bg-surface-container-high",
      "text-on-surface-variant",
      "pl-2.5",
      "pr-1",
      "text-xs",
      "font-medium",
      "h-7",
    ],
    delete: [
      "inline-flex",
      "items-center",
      "justify-center",
      "rounded-full",
      "size-5",
      "hover:bg-on-surface/10",
      "cursor-pointer",
    ],
    input: [
      "flex-1",
      "min-w-[4rem]",
      "bg-transparent",
      "text-on-surface",
      "outline-none",
      "placeholder:text-on-surface-variant",
    ],
    content: [
      "overflow-hidden",
      "rounded-xl",
      "bg-surface-container",
      "text-on-surface",
      "shadow-[var(--wr-elevation-2)]",
    ],
    item: [
      "md3-state-layer",
      "relative",
      "flex",
      "items-center",
      "rounded-lg",
      "px-3",
      "py-2",
      "text-sm",
      "cursor-pointer",
      "select-none",
      "outline-none",
      "data-[highlighted]:before:opacity-[0.08]",
    ],
    empty: [
      "px-3",
      "py-4",
      "text-center",
      "text-sm",
      "text-on-surface-variant",
    ],
  },
  sizes: {
    sm: ["text-sm", "min-h-10"],
    md: ["text-base", "min-h-14"],
    lg: ["text-lg", "min-h-16"],
  },
  interactions: {
    hover: ["hover:border-on-surface"],
    disabled: [
      "opacity-[0.38]",
      "cursor-not-allowed",
      "bg-surface-container-low",
    ],
  },
};
