[package]
name = "domain-database-inmemory"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
database-inmemory = { path = "../database-inmemory" }
domain = { path = "../domain" }
serde.workspace = true
serde_json.workspace = true
shared = { path = "../shared" }
tokio.workspace = true
