[package]
name = "domain-database-inmemory"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
shared = { path = "../shared" }
domain = { path = "../domain" }
database-inmemory = { path = "../database-inmemory" }
async-trait.workspace = true
serde.workspace = true
chrono.workspace = true
anyhow.workspace = true
tokio.workspace = true
