import type { ComponentRecipe } from "../../types";

export const tagInputRecipe: ComponentRecipe = {
  base: [],
  variants: {
    root: [
      "flex",
      "flex-wrap",
      "items-center",
      "gap-1",
      "w-full",
      "rounded-md",
      "border",
      "border-outline-variant",
      "bg-surface",
      "px-2",
      "py-1",
      "transition-colors",
      "duration-normal",
      "ease-standard",
      "focus-within:border-primary",
      "focus-within:outline-2",
      "focus-within:outline-offset-0",
      "focus-within:outline-primary",
    ],
    delete: [
      "inline-flex",
      "items-center",
      "justify-center",
      "rounded-full",
      "size-4",
      "hover:bg-black/10",
      "cursor-pointer",
    ],
    input: [
      "flex-1",
      "min-w-[4rem]",
      "bg-transparent",
      "text-on-surface",
      "outline-none",
      "placeholder:text-on-surface-variant",
    ],
    content: [
      "overflow-hidden",
      "rounded-md",
      "border",
      "border-outline-variant",
      "bg-surface",
      "text-on-surface",
      "shadow-lg",
    ],
    item: [
      "relative",
      "flex",
      "items-center",
      "rounded-sm",
      "px-2",
      "py-1.5",
      "text-sm",
      "cursor-pointer",
      "select-none",
      "outline-none",
      "data-[highlighted]:bg-surface-variant",
      "data-[highlighted]:text-on-surface-variant",
    ],
    empty: [
      "px-2",
      "py-4",
      "text-center",
      "text-sm",
      "text-on-surface-variant",
    ],
  },
  sizes: {
    sm: ["text-sm", "min-h-8"],
    md: ["text-sm", "min-h-10"],
    lg: ["text-base", "min-h-12"],
  },
  interactions: {
    hover: ["hover:border-outline"],
    disabled: ["opacity-50", "cursor-not-allowed", "bg-surface-variant"],
  },
};
